# é”šç‚¹åŒº
Proxy_first: &Proxy_first {type: select, proxies: [èŠ‚ç‚¹é€‰æ‹©, é¦™æ¸¯è‡ªåŠ¨, æ–°åŠ å¡è‡ªåŠ¨, æ—¥æœ¬è‡ªåŠ¨, å°æ¹¾è‡ªåŠ¨, ç¾å›½è‡ªåŠ¨, æ•…éšœè½¬ç§», é¦™æ¸¯èŠ‚ç‚¹, æ–°åŠ å¡èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç¾å›½èŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¨éƒ¨èŠ‚ç‚¹, è‡ªå»º/å®¶å®½èŠ‚ç‚¹, å…¨çƒç›´è¿]}

Direct_first: &Direct_first {type: select, proxies: [å…¨çƒç›´è¿, èŠ‚ç‚¹é€‰æ‹©, é¦™æ¸¯è‡ªåŠ¨, æ–°åŠ å¡è‡ªåŠ¨, æ—¥æœ¬è‡ªåŠ¨, å°æ¹¾è‡ªåŠ¨, ç¾å›½è‡ªåŠ¨, æ•…éšœè½¬ç§», é¦™æ¸¯èŠ‚ç‚¹, æ–°åŠ å¡èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç¾å›½èŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¨éƒ¨èŠ‚ç‚¹, è‡ªå»º/å®¶å®½èŠ‚ç‚¹]}

Include_all: &Include_all {type: select, proxies: [èŠ‚ç‚¹é€‰æ‹©, é¦™æ¸¯è‡ªåŠ¨, æ–°åŠ å¡è‡ªåŠ¨, æ—¥æœ¬è‡ªåŠ¨, å°æ¹¾è‡ªåŠ¨, ç¾å›½è‡ªåŠ¨, æ•…éšœè½¬ç§», é¦™æ¸¯èŠ‚ç‚¹, æ–°åŠ å¡èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç¾å›½èŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¨éƒ¨èŠ‚ç‚¹, è‡ªå»º/å®¶å®½èŠ‚ç‚¹, å…¨çƒç›´è¿], include-all: true, exclude-filter: "(?i)(ğŸŸ¢ ç›´è¿)"}

# æœºåœºè®¢é˜…ï¼ŒAirport_01/02/03åç§°ä¸èƒ½é‡å¤,ä½†å¯ä¿®æ”¹ä¸ºè‡ªå·±å–œæ¬¢çš„

proxy-providers:
  Airport_01:
    type: http
    interval: 86400
    health-check:
      enable: true
      url: 'https://edge.microsoft.com/captiveportal/generate_204'
      interval: 300
    exclude-filter: >-
      (?i)(æ‹’ç»|ç›´è¿|ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|traffic)
    proxy: "ğŸŸ¢ ç›´è¿"
    url: >-
      è®¢é˜…é“¾æ¥1
    override:
      additional-prefix: '[æœºåœºåç§°1] '
      skip-cert-verify: true
      udp: true
  Airport_02:
    type: http
    interval: 86400
    health-check:
      enable: true
      url: 'https://edge.microsoft.com/captiveportal/generate_204'
      interval: 300
    exclude-filter: >-
      (?i)(æ‹’ç»|ç›´è¿|ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|traffic)
    proxy: "ğŸŸ¢ ç›´è¿"
    url: >-
      è®¢é˜…é“¾æ¥2
    override:
      additional-prefix: '[æœºåœºåç§°2] '
      skip-cert-verify: true
      udp: true
  Airport_03:
    type: http
    interval: 86400
    health-check:
      enable: true
      url: 'https://edge.microsoft.com/captiveportal/generate_204'
      interval: 300
    exclude-filter: >-
      (?i)(æ‹’ç»|ç›´è¿|ç¾¤|é‚€è¯·|è¿”åˆ©|å¾ªç¯|å®˜ç½‘|å®¢æœ|ç½‘ç«™|ç½‘å€|è·å–|è®¢é˜…|æµé‡|åˆ°æœŸ|æœºåœº|ä¸‹æ¬¡|ç‰ˆæœ¬|å®˜å€|å¤‡ç”¨|è¿‡æœŸ|å·²ç”¨|è”ç³»|é‚®ç®±|å·¥å•|è´©å–|é€šçŸ¥|å€’å–|é˜²æ­¢|å›½å†…|åœ°å€|é¢‘é“|æ— æ³•|è¯´æ˜|ä½¿ç”¨|æç¤º|ç‰¹åˆ«|è®¿é—®|æ”¯æŒ|æ•™ç¨‹|å…³æ³¨|æ›´æ–°|ä½œè€…|åŠ å…¥|USE|USED|TOTAL|EXPIRE|EMAIL|Panel|Channel|Author|traffic)
    proxy: "ğŸŸ¢ ç›´è¿"
    url: >-
      è®¢é˜…é“¾æ¥3
    override:
      additional-prefix: '[æœºåœºåç§°3] '
      skip-cert-verify: true
      udp: true


# ç”¨äºä¸‹è½½è®¢é˜…æ—¶æŒ‡å®šUA
global-ua: clash.meta

# å…¨å±€é…ç½®
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7894
ipv6: true
allow-lan: true
unified-delay: true
tcp-concurrent: true
# interface-name: eth0  ï¼ˆè·¯ç”±å™¨ä¸‹æ ¹æ®æƒ…å†µæŒ‡å®šå‡ºç«™æ¥å£ï¼‰
authentication:
#  å¯†ç è®¾ç½®é€‰é¡¹é»˜è®¤æ— 
- ""
skip-auth-prefixes:
- 127.0.0.1/8
- ::1/128

geodata-mode: false
# GEO æ–‡ä»¶åŠ è½½æ¨¡å¼ï¼ˆstandardï¼šæ ‡å‡†åŠ è½½å™¨/memconservativeï¼šä¸“ä¸ºå†…å­˜å—é™ (å°å†…å­˜) è®¾å¤‡ä¼˜åŒ–çš„åŠ è½½å™¨ (é»˜è®¤å€¼)ï¼‰
geodata-loader: standard
geo-auto-update: true
geo-update-interval: 48
geox-url:
  geosite: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geosite.dat"
  mmdb: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.metadb"
  geoip: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/geoip-lite.dat"
  asn: "https://github.com/MetaCubeX/meta-rules-dat/releases/download/latest/GeoLite2-ASN.mmdb"

# æ§åˆ¶é¢æ¿
external-controller: 0.0.0.0:9090
secret: ""
#  å¯†ç è®¾ç½®é€‰é¡¹é»˜è®¤æ— 
external-ui: ui
external-ui-url: "https://github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip"
# ä¸‹è½½é¢æ¿åœ°å€å¯æ›´æ¢ï¼šhttps://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip

# åŒ¹é…è¿›ç¨‹ always/strict/off
find-process-mode: strict
global-client-fingerprint: chrome
keep-alive-idle: 600
keep-alive-interval: 30

# ç­–ç•¥ç»„é€‰æ‹©å’Œfakeipç¼“å­˜
profile:
  store-selected: true
  store-fake-ip: false

# æµé‡å—…æ¢
sniffer:
  enable: true
  sniff:
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true
    TLS:
      ports: [443, 8443]
    QUIC:
      ports: [443, 8443]
  force-domain:
    - "*.v2ex.com"
  skip-domain:
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "*.push.apple.com"
    - "*.apple.com"
    - "*.wechat.com"
    - "*.qpic.cn"
    - "*.qq.com"
    - "*.wechatapp.com"
    - "*.vivox.com"
    # å‘æ—¥è‘µæœåŠ¡
    - "*.oray.com"
    - "*.sunlogin.net"

# ä»£ç†æ¨¡å¼
tun:
  enable: true
  stack: system
  mtu: 9000
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-route: true
  auto-redirect: true
  auto-detect-interface: true

# DNSæ¨¡å—
dns:
  enable: true
  listen: 0.0.0.0:1053
  ipv6: true
  prefer-h3: true # æ˜¯å¦å¼€å¯ DoH æ”¯æŒ HTTP/3ï¼Œå°†å¹¶å‘å°è¯•
  respect-rules: true
  # æ¨¡å¼åˆ‡æ¢ redir-host / fake-ip
  enhanced-mode: fake-ip
  fake-ip-range: 28.0.0.1/8
  # æ¨¡å¼åˆ‡æ¢ whitelist/blacklist 
  # é»‘åå•æ¨¡å¼è¡¨ç¤ºå¦‚æœåŒ¹é…æˆåŠŸåˆ™ä¸è¿”å› Fake-IP, ç™½åå•æ¨¡å¼æ—¶åªæœ‰åŒ¹é…æˆåŠŸæ‰è¿”å› Fake-IP
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - "*.lan"
    - "*.local"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time-ios.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "*.pool.ntp.org"
    - "+.services.googleapis.cn"
    - "+.xn--ngstr-lra8j.com"
    - "+.push.apple.com"
    - 5ddd.com
    - time1.cloud.tencent.com
  default-nameserver:
    - 223.5.5.5
    - 119.29.29.29
  proxy-server-nameserver:
    - quic://dns.alidns.com/dns-query
    - https://sm2.doh.pub/dns-query 
  nameserver:
    - quic://dns.alidns.com/dns-query
    - https://sm2.doh.pub/dns-query

proxies: 
  - name: "ğŸŸ¢ ç›´è¿"
    type: direct
    udp: true        





# ç­–ç•¥ç»„
proxy-groups:
  - {name: èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [é¦™æ¸¯è‡ªåŠ¨, æ–°åŠ å¡è‡ªåŠ¨, æ—¥æœ¬è‡ªåŠ¨, å°æ¹¾è‡ªåŠ¨, ç¾å›½è‡ªåŠ¨, æ•…éšœè½¬ç§», é¦™æ¸¯èŠ‚ç‚¹, æ–°åŠ å¡èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç¾å›½èŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, å…¨éƒ¨èŠ‚ç‚¹, è‡ªå»º/å®¶å®½èŠ‚ç‚¹, ğŸŸ¢ ç›´è¿], icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/select.png"}
  - {name: YouTube, <<: *Proxy_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/youtube.png"}
  - {name: Google, <<: *Proxy_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/google.png"}
  - {name: Meta, <<: *Proxy_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/meta.png"}
  - {name: AI, <<: *Include_all, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/ai.png"}
  - {name: GitHub, <<: *Proxy_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/github.png"}
  - {name: OneDrive, <<: *Proxy_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/onedrive.png"}
  - {name: Microsoft, <<: *Proxy_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/microsoft.png"}
  - {name: Telegram, <<: *Proxy_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/telegram.png"}
  - {name: TikTok, <<: *Proxy_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/tiktok.png"}
  - {name: NETFLIX, <<: *Proxy_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/netfix.png"}
  - {name: DisneyPlus, <<: *Proxy_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/disneyplus.png"}
  - {name: HBO, <<: *Proxy_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/hbo.png"}
  - {name: Apple, type: select, <<: *Direct_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/apple.png"}
  - {name: Emby,type: select, <<: *Include_all, include-all: true, icon: https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/emby.png}
  - {name: å“”å“©å“”å“©, type: select, <<: *Direct_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/bilibili.png"}
  - {name: å“”å“©ä¸œå—äºš, type: select, proxies: [èŠ‚ç‚¹é€‰æ‹©, æ–°åŠ å¡è‡ªåŠ¨, æ–°åŠ å¡èŠ‚ç‚¹, å…¨éƒ¨èŠ‚ç‚¹, è‡ªå»º/å®¶å®½èŠ‚ç‚¹, å…¨çƒç›´è¿], icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/bilibilit.png"}
  - {name: å·´å“ˆå§†ç‰¹, type: select, proxies: [å°æ¹¾èŠ‚ç‚¹, å°æ¹¾è‡ªåŠ¨], icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/bahamut.png"}
  - {name: Spotify, <<: *Proxy_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/spotify.png"}
  - {name: å›½å†…åª’ä½“, type: select, <<: *Direct_first, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/Chinese_media.png"}
  - {name: STEAM,type: select, <<: *Include_all, icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/steam.png"}
  - {name: å…¨çƒç›´è¿, type: select, proxies: [ğŸŸ¢ ç›´è¿, èŠ‚ç‚¹é€‰æ‹©], icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/direct.png"}
  - {name: éšç§æ‹¦æˆª, type: select, proxies: [REJECT, DIRECT], icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/block.png"}
  - {name: Final, type: select, <<: *Include_all,  icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/final.png"}
  - {name: è‡ªå»º/å®¶å®½èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(è‡ªå»º|CF|The_house|private)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/private_node.png"}
  - {name: é¦™æ¸¯èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(æ¸¯|hk|hongkong|Hong Kong)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/Hongkong.png"}
  - {name: æ–°åŠ å¡èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(æ–°|ğŸ‡¸ğŸ‡¬|SG|singapore)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/Singapore.png"}
  - {name: æ—¥æœ¬èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|Japan)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/Japan.png"}
  - {name: å°æ¹¾èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(å°|ğŸ‡¹ğŸ‡¼|TW|Taiwan)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/Taiwan_China.png"}
  - {name: ç¾å›½èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(ç¾|ğŸ‡ºğŸ‡²|US|America|United States)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/America.png"}
  - {name: æ¬§æ´²èŠ‚ç‚¹, type: select, include-all: true, filter: "(?i)(ğŸ‡¦ğŸ‡±|ğŸ‡¦ğŸ‡©|ğŸ‡¦ğŸ‡¹|ğŸ‡§ğŸ‡¾|ğŸ‡§ğŸ‡ª|ğŸ‡§ğŸ‡¦|ğŸ‡§ğŸ‡¬|ğŸ‡­ğŸ‡·|ğŸ‡¨ğŸ‡¾|ğŸ‡¨ğŸ‡¿|ğŸ‡©ğŸ‡°|ğŸ‡ªğŸ‡ª|ğŸ‡«ğŸ‡®|ğŸ‡«ğŸ‡·|ğŸ‡©ğŸ‡ª|ğŸ‡¬ğŸ‡·|ğŸ‡­ğŸ‡º|ğŸ‡®ğŸ‡¸|ğŸ‡®ğŸ‡ª|ğŸ‡®ğŸ‡¹|ğŸ‡½ğŸ‡°|ğŸ‡±ğŸ‡»|ğŸ‡±ğŸ‡®|ğŸ‡±ğŸ‡¹|ğŸ‡±ğŸ‡º|ğŸ‡²ğŸ‡¹|ğŸ‡²ğŸ‡©|ğŸ‡²ğŸ‡¨|ğŸ‡²ğŸ‡ª|ğŸ‡³ğŸ‡±|ğŸ‡²ğŸ‡°|ğŸ‡³ğŸ‡´|ğŸ‡µğŸ‡±|ğŸ‡µğŸ‡¹|ğŸ‡·ğŸ‡´|ğŸ‡·ğŸ‡º|ğŸ‡¸ğŸ‡²|ğŸ‡·ğŸ‡¸|ğŸ‡¸ğŸ‡°|ğŸ‡¸ğŸ‡®|ğŸ‡ªğŸ‡¸|ğŸ‡¸ğŸ‡ª|ğŸ‡¨ğŸ‡­|ğŸ‡¹ğŸ‡·|ğŸ‡ºğŸ‡¦|ğŸ‡¬ğŸ‡§|ğŸ‡»ğŸ‡¦)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/European.png"}
  - {name: é¦™æ¸¯è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)(é¦™æ¸¯|hk|hongkong|Hong Kong)" ,exclude-filter: "(?i)(The_HK_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|traffic|plus)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/automation2.png"}
  - {name: æ–°åŠ å¡è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)(æ–°|ğŸ‡¸ğŸ‡¬|SG|Singapore)" ,exclude-filter: "(?i)(The_SG_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|traffic|plus)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/automation2.png"}
  - {name: æ—¥æœ¬è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)(æ—¥æœ¬|ğŸ‡¯ğŸ‡µ|JP|Japan)" ,exclude-filter: "(?i)(The_JP_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|traffic|plus)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/automation2.png"}
  - {name: å°æ¹¾è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)(å°|ğŸ‡¹ğŸ‡¼|TW|Taiwan)" ,exclude-filter: "(?i)(The_TW_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|traffic|plus)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/automation2.png"}
  - {name: ç¾å›½è‡ªåŠ¨, type: url-test, include-all: true, tolerance: 20, interval: 300, filter: "(?i)(ç¾|ğŸ‡ºğŸ‡²|US|America|united States)" ,exclude-filter: "(?i)(The_US_automation|wcloud|0å€|0\\.1å€|0\\.01å€|0\\.3X|0\\.2x|0\\.5x|3X|2x|1\\.5x|russia|austria|plus|traffic|Australia|rus|aus)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/automation2.png"}
  - {name: æ•…éšœè½¬ç§», type: fallback, include-all: true, interval: 300, exclude-filter: "(?i)(ğŸŸ¢ ç›´è¿)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/fallback.png"}
  - {name: å…¨éƒ¨èŠ‚ç‚¹, type: select, include-all: true, tolerance: 20, interval: 300, exclude-filter: "(?i)(ğŸŸ¢ ç›´è¿)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/all.png"}
  - {name: GLOBAL, type: select, include-all: true , proxies: [èŠ‚ç‚¹é€‰æ‹©, YouTube, Google, Meta, AI, GitHub, OneDrive, Microsoft, Telegram, TikTok, NETFLIX, DisneyPlus, HBO, Apple, Emby, å“”å“©å“”å“©, å“”å“©ä¸œå—äºš, å·´å“ˆå§†ç‰¹, Spotify, å›½å†…åª’ä½“, STEAM, å…¨çƒç›´è¿, éšç§æ‹¦æˆª, Final, è‡ªå»º/å®¶å®½èŠ‚ç‚¹, é¦™æ¸¯èŠ‚ç‚¹, æ–°åŠ å¡èŠ‚ç‚¹, æ—¥æœ¬èŠ‚ç‚¹, å°æ¹¾èŠ‚ç‚¹, ç¾å›½èŠ‚ç‚¹, æ¬§æ´²èŠ‚ç‚¹, é¦™æ¸¯è‡ªåŠ¨, æ–°åŠ å¡è‡ªåŠ¨, æ—¥æœ¬è‡ªåŠ¨, å°æ¹¾è‡ªåŠ¨, ç¾å›½è‡ªåŠ¨, æ•…éšœè½¬ç§», å…¨éƒ¨èŠ‚ç‚¹], exclude-filter: "(?i)(ğŸŸ¢ ç›´è¿)", icon: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/icon/global.png"}
rules: 
  - GEOSITE,category-ads-all,éšç§æ‹¦æˆª
  - GEOSITE,private,å…¨çƒç›´è¿
  - GEOIP,private,å…¨çƒç›´è¿,no-resolve
  - GEOSITE,category-games@cn,å…¨çƒç›´è¿
  - GEOSITE,category-public-tracker,å…¨çƒç›´è¿
  - GEOSITE,openai,AI
  - GEOSITE,category-ai-!cn,AI
  - RULE-SET,ai_domain,AI
  - GEOSITE,youtube,YouTube
  - GEOSITE,google,Google
  - GEOSITE,github,GitHub
  - GEOSITE,onedrive,OneDrive
  - GEOSITE,microsoft,Microsoft
  - GEOSITE,apple,Apple
  - GEOSITE,telegram,Telegram
  - GEOIP,telegram,Telegram,no-resolve
  - GEOSITE,facebook,Meta
  - GEOSITE,netflix,NETFLIX
  - GEOSITE,disney,DisneyPlus
  - GEOSITE,hbo,HBO
  - RULE-SET,emby_domain,Emby
  - GEOSITE,spotify,Spotify
  - GEOSITE,bahamut,å·´å“ˆå§†ç‰¹
  - GEOSITE,tiktok,TikTok
  - GEOSITE,bilibili,å“”å“©å“”å“©
  - GEOSITE,biliintl,å“”å“©ä¸œå—äºš
  - GEOSITE,category-media-cn,å›½å†…åª’ä½“
  - GEOSITE,steam,STEAM
  - GEOIP,twitter,èŠ‚ç‚¹é€‰æ‹©,no-resolve
  - GEOIP,ai,AI,no-resolve
  - GEOSITE,gfw,èŠ‚ç‚¹é€‰æ‹©
  - GEOSITE,geolocation-!cn,èŠ‚ç‚¹é€‰æ‹©
  - GEOSITE,cn,å…¨çƒç›´è¿
  - GEOIP,cn,å…¨çƒç›´è¿,no-resolve
  - MATCH,Final
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  ip_text: &ip_text {type: http, interval: 86400, behavior: ipcidr, format: text}
  ip_yaml: &ip_yaml {type: http, interval: 86400, behavior: ipcidr, format: yaml}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  domain_text: &domain_text {type: http, interval: 86400, behavior: domain, format: text}
  domain_yaml: &domain_yaml {type: http, interval: 86400, behavior: domain, format: yaml}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}
  class_yaml: &class_yaml {type: http, interval: 86400, behavior: classical, format: yaml}
rule-providers: 
  emby_domain: { <<: *domain, url: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/emby.mrs" }
  ai_domain: { <<: *domain, url: "https://raw.githubusercontent.com/Lanlan13-14/Rules/refs/heads/main/rules/Domain/ai.mrs" }